/* @ts-nocheck */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated TypeScript interfaces from Swagger specification
 * Do not edit this file manually
 */
import { HttpContext, HttpHeaders } from '@angular/common/http';
export interface User {
  id: string;
  name: string;
  displayName: string;
  description: string;
  type: string;
  broadcasterType: string;
  profilePictureUrl: string;
  offlinePlaceholderUrl: string;
  creationDate: string;
}

export enum EmoteType {
  Seventvemote = 'seventvemote',
  Ffzemote = 'ffzemote',
  Bttvemote = 'bttvemote',
  Twitchemote = 'twitchemote',
}

export interface Emote {
  name: string;
  link: string;
  type: EmoteType;
}

export interface Badge {
  name: string;
  link: string;
}

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
  headers?: HttpHeaders;
  reportProgress?: boolean;
  responseType?: TResponseType;
  withCredentials?: boolean;
  context?: HttpContext;
}
