/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
 * Generated by ng-openapi
 * Generated Angular service for Users controller
 * Do not edit this file manually
 */
import {
  HttpClient,
  HttpContext,
  HttpContextToken,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse,
} from '@angular/common/http';
import { inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BASE_PATH_SPAMMERINOAPI, CLIENT_CONTEXT_TOKEN_SPAMMERINOAPI } from '../tokens';
import { HttpParamsBuilder } from '../utils/http-params-builder';
import { RequestOptions, User, Emote, Badge } from '../models';

@Injectable({ providedIn: 'root' })
export class UsersService {
  private readonly httpClient: HttpClient = inject(HttpClient);
  private readonly basePath: string = inject(BASE_PATH_SPAMMERINOAPI);
  private readonly clientContextToken: HttpContextToken<string> =
    CLIENT_CONTEXT_TOKEN_SPAMMERINOAPI;

  private createContextWithClientId(existingContext?: HttpContext): HttpContext {
    const context = existingContext || new HttpContext();
    return context.set(this.clientContextToken, 'SpammerinoApi');
  }

  searchUsers(
    userName: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<Array<User>>;
  searchUsers(
    userName: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<Array<User>>>;
  searchUsers(
    userName: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<Array<User>>>;
  searchUsers(
    userName: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/users/search/${userName}`;

    const requestOptions: any = {
      observe: observe as any,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  getUserByUsername(
    userName: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<User>;
  getUserByUsername(
    userName: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<User>>;
  getUserByUsername(
    userName: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<User>>;
  getUserByUsername(
    userName: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/users/${userName}`;

    const requestOptions: any = {
      observe: observe as any,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  getEmotesByUsername(
    userName: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<Array<Emote>>;
  getEmotesByUsername(
    userName: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<Array<Emote>>>;
  getEmotesByUsername(
    userName: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<Array<Emote>>>;
  getEmotesByUsername(
    userName: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/users/${userName}/emotes`;

    const requestOptions: any = {
      observe: observe as any,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }

  getBadgesByUsername(
    userName: string,
    observe?: 'body',
    options?: RequestOptions<'json'>,
  ): Observable<Array<Badge>>;
  getBadgesByUsername(
    userName: string,
    observe?: 'response',
    options?: RequestOptions<'json'>,
  ): Observable<HttpResponse<Array<Badge>>>;
  getBadgesByUsername(
    userName: string,
    observe?: 'events',
    options?: RequestOptions<'json'>,
  ): Observable<HttpEvent<Array<Badge>>>;
  getBadgesByUsername(
    userName: string,
    observe?: 'body' | 'events' | 'response',
    options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>,
  ): Observable<any> {
    const url = `${this.basePath}/users/${userName}/badges`;

    const requestOptions: any = {
      observe: observe as any,
      reportProgress: options?.reportProgress,
      withCredentials: options?.withCredentials,
      context: this.createContextWithClientId(options?.context),
    };

    return this.httpClient.get(url, requestOptions);
  }
}
